version: "3.8"
name: notebook-prod

services:
  front-end:
    build:
      context: ./front-end
    container_name: front-end
    ports:
      - "4001:3000"
  back-end:
    container_name: back-end
    build:
      context: ./back-end
      dockerfile: Dockerfile
    ports:
      - "4002:8080"
    volumes:
      - ${NOTEBOOK_FOLDER}:/app/notebooks
    environment:
      - NOTEBOOK_PATH=/app/notebooks
    env_file:
      - .env
