version: '3.8'

services:
  front-end:
    build:
      context: ./front-end
    container_name: front-end
    ports:
      - "3000:3000"
    volumes:
      - ./front-end:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
