version: "3.8"

services:
  front-end:
    build:
      context: ./front-end
    container_name: front-end
    ports:
      - "3000:3000"
    volumes:
      - ./front-end:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
  back-end:
    container_name: back-end
    build:
      context: ./back-end
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ${NOTEBOOK_FOLDER:-/Users/jeroen/Notes}:/app/notebooks
    environment:
      - NOTEBOOK_PATH=/app/notebooks
